name: Master CI/CD
on:
  push:
    branches: master

jobs:
  Deploy-Patent-Bot:
    uses: ./.github/deploy.yml
    with:
      ecr_repo_name: ${{ secrets.PATENT_BOT_ECR_REPO_NAME }}
      lambda_function_name: ${{ vars.PATENT_BOT_LAMBDA_FUNCTION_NAME }}

  Deploy-Weather-Bot:
    uses: ./.github/deploy.yml
    with:
      ecr_repo_name: ${{ secrets.WEATHER_BOT_ECR_REPO_NAME }}
      lambda_function_name: ${{ vars.WEATHER_BOT_LAMBDA_FUNCTION_NAME }}